# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('washer', '0002_register'),
    ]

    operations = [
    ]
